# Copyright © 2024 Brent Tunnicliff <brent@tunnicliff.dev>

name: 'Setup for pipeline'
description: 'Common setup for my Android pipelines'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      shell: bash
      run: chmod +x gradlew